/**
 * Signing Session Management
 *
 * Creates and manages signature requests. A signing session represents
 * a document sent for e-signature to one or more signers.
 */

import { query } from '../db.js';
import { createChildLogger } from '../logger.js';

// Current hash formula version. Matches the default in migration 063.
// Bump only in lock-step with a new compute_document_hash() branch.
const CURRENT_HASH_VERSION = 2;

const log = createChildLogger({ module: 'signatures/session' });

const SIGNING_BASE_URL = process.env.SIGNING_BASE_URL || 'https://board.staqs.io';

/**
 * Create a signing request and generate signing URLs for each signer.
 *
 * @param {Object} opts
 * @param {string} opts.draftId - UUID of content.drafts row
 * @param {string} opts.title - Document title
 * @param {string} opts.message - Cover message to signers
 * @param {Array<{name: string, email: string, order?: number}>} opts.signers
 * @param {string} opts.createdBy - Board member who initiated
 * @param {number} [opts.expiresInHours=72] - Hours until expiry
 * @param {string} [opts.signingMode='parallel'] - 'parallel' or 'sequential'
 * @returns {Promise<{requestId: string, signers: Array<{email: string, signingUrl: string}>, expiresAt: Date}>}
 */
export async function createSigningRequest(opts) {
  const {
    draftId, title, message, signers, createdBy,
    expiresInHours = 72, signingMode = 'parallel',
  } = opts;

  // Verify draft exists before asking the DB to hash it
  const draftResult = await query(
    `SELECT 1 FROM content.drafts WHERE id = $1`,
    [draftId]
  );
  if (!draftResult.rows.length) {
    throw new Error(`Draft ${draftId} not found`);
  }

  // Compute the canonical hash anchor via the DB function so body + attachments
  // are combined using the exact same formula the signer endpoint will re-run
  // at sign time. Never hash in Node — that invites formula drift.
  const hashResult = await query(
    `SELECT signatures.compute_document_hash($1, $2) AS hash`,
    [draftId, CURRENT_HASH_VERSION]
  );
  const documentHash = hashResult.rows[0].hash;

  const expiresAt = new Date(Date.now() + expiresInHours * 60 * 60 * 1000);

  // Create signature request (hash_version stamped explicitly so future formula
  // upgrades don't silently retarget this row)
  const reqResult = await query(
    `INSERT INTO signatures.signature_requests
       (draft_id, document_hash, hash_version, title, message, signing_mode, expires_at, created_by)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
     RETURNING id`,
    [draftId, documentHash, CURRENT_HASH_VERSION, title, message, signingMode, expiresAt, createdBy]
  );

  const requestId = reqResult.rows[0].id;

  // Create signers (tokens auto-generated by DB default)
  const signerResults = [];
  for (const signer of signers) {
    const signerResult = await query(
      `INSERT INTO signatures.signers (request_id, email, display_name, signing_order)
       VALUES ($1, $2, $3, $4)
       RETURNING id, signing_token`,
      [requestId, signer.email, signer.name, signer.order || null]
    );

    const row = signerResult.rows[0];
    const signingUrl = `${SIGNING_BASE_URL}/sign/${row.signing_token}`;

    signerResults.push({
      signerId: row.id,
      email: signer.email,
      name: signer.name,
      signingUrl,
      token: row.signing_token,
    });
  }

  log.info({ requestId, draftId, signerCount: signers.length, expiresAt }, 'Signing request created');

  return { requestId, signers: signerResults, expiresAt, documentHash };
}

/**
 * Get a signing request by ID with signer details.
 */
export async function getRequest(requestId) {
  const result = await query(
    `SELECT sr.*,
       json_agg(json_build_object(
         'id', s.id, 'email', s.email, 'display_name', s.display_name,
         'status', s.status, 'signing_order', s.signing_order,
         'completed_at', s.completed_at
       ) ORDER BY s.signing_order NULLS LAST) AS signers
     FROM signatures.signature_requests sr
     LEFT JOIN signatures.signers s ON s.request_id = sr.id
     WHERE sr.id = $1
     GROUP BY sr.id`,
    [requestId]
  );
  return result.rows[0] || null;
}

/**
 * List signing requests with optional filters.
 */
export async function listRequests(filters = {}) {
  const conditions = [];
  const params = [];
  let i = 1;

  if (filters.status) {
    conditions.push(`sr.status = $${i++}`);
    params.push(filters.status);
  }
  if (filters.createdBy) {
    conditions.push(`sr.created_by = $${i++}`);
    params.push(filters.createdBy);
  }
  if (filters.draftId) {
    conditions.push(`sr.draft_id = $${i++}`);
    params.push(filters.draftId);
  }

  const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';

  const result = await query(
    `SELECT sr.*,
       (SELECT count(*) FROM signatures.signers s WHERE s.request_id = sr.id AND s.status = 'signed') AS signed_count,
       (SELECT count(*) FROM signatures.signers s WHERE s.request_id = sr.id) AS total_signers
     FROM signatures.signature_requests sr
     ${where}
     ORDER BY sr.created_at DESC
     LIMIT 50`,
    params
  );

  return result.rows;
}

/**
 * Revoke a pending signing request.
 */
export async function revokeRequest(requestId, reason) {
  await query(
    `UPDATE signatures.signature_requests
     SET status = 'cancelled', updated_at = now()
     WHERE id = $1 AND status IN ('pending', 'in_progress')`,
    [requestId]
  );

  // Expire all pending signers
  await query(
    `UPDATE signatures.signers
     SET status = 'expired', updated_at = now()
     WHERE request_id = $1 AND status = 'pending'`,
    [requestId]
  );

  log.info({ requestId, reason }, 'Signing request revoked');
}

/**
 * Look up a signer by their signing token (public endpoint).
 */
export async function getSignerByToken(token) {
  const result = await query(
    `SELECT s.*, sr.title, sr.document_hash, sr.hash_version, sr.status AS request_status,
       sr.expires_at, sr.draft_id, sr.message
     FROM signatures.signers s
     JOIN signatures.signature_requests sr ON sr.id = s.request_id
     WHERE s.signing_token = $1`,
    [token]
  );
  return result.rows[0] || null;
}

/**
 * Get the document body for a signing session (frozen snapshot from draft).
 */
export async function getDocumentBody(draftId) {
  const result = await query(
    `SELECT body, title FROM content.drafts WHERE id = $1`,
    [draftId]
  );
  return result.rows[0] || null;
}
