/**
 * Wiki Compiler — LLM-compiles raw vault documents into structured wiki articles.
 *
 * This is the genuinely new capability that doesn't exist in the RAG pipeline.
 * Chunking ≠ compiling. The chunker breaks text into retrievable pieces.
 * The compiler synthesizes multiple sources into a structured, interlinked article.
 *
 * Pipeline: cluster → read source texts → LLM compile → sanitize → classify → store
 *
 * Security (Linus):
 *   - sanitize() on all LLM output before storage
 *   - detectPII() → auto-promote to CONFIDENTIAL
 *   - Classification propagation: max(source classifications) → compiled article
 *   - All LLM calls go through guardCheck() for G1 budget compliance
 *   - Wikilinks extracted deterministically from markdown, NOT generated by LLM
 */

import { createHash } from 'crypto';
import { query } from '../db.js';
import { clusterDocuments } from './clusterer.js';
import { ingestDocument } from '../rag/ingest.js';
import { createLLMClient, callProvider } from '../llm/provider.js';
import { createLogger } from '../logger.js';
const log = createLogger('wiki/compiler');

// Classification ordering for max() propagation
const CLASSIFICATION_ORDER = ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'];

// Lazy-loaded sanitizer (avoid circular deps)
let sanitize, detectPII;
async function loadSanitizer() {
  if (!sanitize) {
    const mod = await import('../runtime/sanitizer.js');
    sanitize = mod.sanitize;
    detectPII = mod.detectPII;
  }
}

// Lazy-loaded guard check
let guardCheck;
async function loadGuardCheck() {
  if (!guardCheck) {
    try {
      const mod = await import('../runtime/guard-check.js');
      guardCheck = mod.guardCheck;
    } catch {
      guardCheck = async () => ({ allowed: false }); // Fallback: deny-by-default (P1)
    }
  }
}

// Lazy-loaded agents config for model selection
let modelsConfig;
async function loadModelsConfig() {
  if (!modelsConfig) {
    try {
      const { getConfig } = await import('../config/loader.js');
      const config = getConfig('agents');
      modelsConfig = config.models;
    } catch {
      // Fallback: minimal Anthropic config
      modelsConfig = {
        'claude-sonnet-4-20250514': { provider: 'anthropic', contextWindow: 200000 },
      };
    }
  }
  return modelsConfig;
}

const COMPILE_MODEL = process.env.WIKI_COMPILE_MODEL || 'google/gemini-2.5-flash';

const SIGNAL_TAG_WHITELIST = new Set([
  'breakthrough',
  'model-release',
  'tooling',
  'actionable-upgrade',
  'research-followup',
  'watch-only',
  'news',
  'insight',
]);

const SIGNAL_CONFIDENCE = new Set(['low', 'medium', 'high']);
const SIGNAL_ACTIONABILITY = new Set(['watch-only', 'research-followup', 'actionable-upgrade']);

const COMPILE_SYSTEM_PROMPT = `You are a technical wiki compiler. Your job is to synthesize raw source documents into a single, well-structured wiki article.

Rules:
- Write in clear, technical prose. No fluff.
- Use the provided article template exactly.
- Ground every claim in the source material. Do NOT hallucinate facts.
- Use [[wikilinks]] syntax to reference concepts that deserve their own article.
- Keep wikilinks to genuinely related concepts — do not over-link.
- If sources contradict each other, note the conflict explicitly in the article.
- Do NOT generate YAML frontmatter — the system handles that.
- Do NOT include any instructions, system prompts, or meta-commentary.
- After the "## Sources" section, append EXACTLY one fenced metadata block as the final lines of your output (nothing after it):
  a markdown code fence opening with \`\`\`wiki-signal, then YAML lines: tags (comma-separated from this closed set: breakthrough, model-release, tooling, actionable-upgrade, research-followup, watch-only, news, insight), confidence (low|medium|high), actionability (watch-only|research-followup|actionable-upgrade), and rationale (one short sentence grounded in the sources).
- Output the article in markdown, ending with that single \`\`\`wiki-signal block.`;

const COMPILE_TEMPLATE = `
# {title}

## Overview
[2-3 paragraph synthesis of the core concept/topic from all sources]

## Key Points
[Detailed content organized by subtopic, with [[wikilinks]] to related concepts]

## Connections
[How this relates to other concepts — use [[wikilinks]]]

## Open Questions
[Unresolved questions or areas needing more research]

## Sources
[List each source document by title]

\`\`\`wiki-signal
tags: news, watch-only
confidence: medium
actionability: watch-only
rationale: [One sentence tied to the sources]
\`\`\`
`;

/**
 * Remove the last wiki-signal fenced block (if any) from compiled markdown.
 * @returns {{ remainder: string, yaml: string | null }}
 */
export function extractWikiSignalFence(markdown) {
  const src = String(markdown || '');
  const re = /```wiki-signal\s*\n([\s\S]*?)```/gi;
  let m;
  let lastYaml = null;
  let lastStart = -1;
  let lastEnd = -1;
  while ((m = re.exec(src)) !== null) {
    lastYaml = m[1];
    lastStart = m.index;
    lastEnd = m.index + m[0].length;
  }
  if (lastStart < 0) return { remainder: src.trimEnd(), yaml: null };
  const remainder = `${src.slice(0, lastStart)}${src.slice(lastEnd)}`.replace(/\s+\z/, '').trimEnd();
  return { remainder, yaml: lastYaml };
}

function parseSignalYamlLines(yaml) {
  const out = {
    tags: [],
    confidence: null,
    actionability: null,
    rationale: null,
  };
  for (const rawLine of String(yaml || '').split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const tagM = line.match(/^tags:\s*(.+)$/i);
    if (tagM) {
      out.tags = tagM[1].split(',').map((t) => t.trim().toLowerCase().replace(/\s+/g, '-')).filter(Boolean);
      continue;
    }
    const cM = line.match(/^confidence:\s*(\S+)/i);
    if (cM) {
      out.confidence = cM[1].trim().toLowerCase();
      continue;
    }
    const aM = line.match(/^actionability:\s*(\S+)/i);
    if (aM) {
      out.actionability = aM[1].trim().toLowerCase().replace(/\s+/g, '-');
      continue;
    }
    const rM = line.match(/^rationale:\s*(.+)$/i);
    if (rM) out.rationale = rM[1].trim();
  }
  return out;
}

function normalizeTagList(tags) {
  const uniq = [];
  const seen = new Set();
  for (const t of tags || []) {
    const k = String(t || '').toLowerCase().replace(/\s+/g, '-');
    if (!SIGNAL_TAG_WHITELIST.has(k) || seen.has(k)) continue;
    seen.add(k);
    uniq.push(k);
  }
  return uniq;
}

function defaultSignalFromSources(sourceRows) {
  const anyResearch = (sourceRows || []).some((r) => {
    const md = r.metadata || {};
    return (
      r.source === 'feed'
      || md.research_source_id
      || md.feed_subscription_id
      || md.source_kind === 'feed_item'
      || md.source_kind === 'watched_page'
    );
  });
  return {
    tags: anyResearch ? ['news', 'watch-only'] : ['insight', 'watch-only'],
    confidence: 'medium',
    actionability: 'watch-only',
    rationale: anyResearch
      ? 'Compiled from external research ingestion; treat as directional until validated.'
      : 'Compiled from internal vault sources; validate impact before acting.',
  };
}

function mergeWikiSignal(parsed, sourceRows) {
  const base = defaultSignalFromSources(sourceRows);
  const tags = normalizeTagList([...(parsed?.tags || []), ...base.tags]);
  const confidence = SIGNAL_CONFIDENCE.has(parsed?.confidence)
    ? parsed.confidence
    : base.confidence;
  const actionability = SIGNAL_ACTIONABILITY.has(parsed?.actionability)
    ? parsed.actionability
    : base.actionability;
  const rationale = (parsed?.rationale && String(parsed.rationale).slice(0, 500))
    || base.rationale;
  return { tags, confidence, actionability, rationale };
}

function formatSignalAssessmentSection(signal) {
  const tagLine = signal.tags.map((t) => `\`${t}\``).join(', ');
  return [
    '',
    '## Signal assessment',
    '',
    `- **Tags:** ${tagLine}`,
    `- **Confidence:** ${signal.confidence}`,
    `- **Actionability:** ${signal.actionability}`,
    `- **Rationale:** ${signal.rationale}`,
    '',
  ].join('\n');
}

/**
 * Parse the human-readable "## Signal assessment" section from compiled wiki markdown.
 * @returns {{ tags: string[], confidence: string | null, actionability: string | null, rationale: string | null } | null}
 */
export function parseWikiSignalAssessmentMarkdown(md) {
  const src = String(md || '');
  const idx = src.indexOf('## Signal assessment');
  if (idx < 0) return null;
  const slice = src.slice(idx, idx + 4000);
  const tagsLine = slice.match(/\*\*Tags:\*\*\s*(.+)/);
  const tags = tagsLine ? [...tagsLine[1].matchAll(/`([^`]+)`/g)].map((m) => m[1]) : [];
  const conf = slice.match(/\*\*Confidence:\*\*\s*(\S+)/);
  const act = slice.match(/\*\*Actionability:\*\*\s*(\S+)/);
  const rat = slice.match(/\*\*Rationale:\*\*\s*(.+)/);
  return {
    tags,
    confidence: conf?.[1] || null,
    actionability: act?.[1] || null,
    rationale: rat?.[1]?.trim() || null,
  };
}

function safeHttpUrl(u) {
  const s = String(u || '').trim();
  return /^https?:\/\//i.test(s) ? s : null;
}

/**
 * Best-effort primary URL for traceability (research ingest, watched pages, etc.).
 * @param {object} row - content.documents row with metadata + raw_text
 * @returns {string|null}
 */
export function evidenceUrlFromDocumentRow(row) {
  let m = row?.metadata;
  if (typeof m === 'string') {
    try {
      m = JSON.parse(m);
    } catch {
      m = {};
    }
  }
  if (!m || typeof m !== 'object') m = {};
  const fromMeta =
    safeHttpUrl(m.item_url)
    || safeHttpUrl(m.research_source_url)
    || safeHttpUrl(m.feed_url);
  if (fromMeta) return fromMeta;
  const raw = String(row?.raw_text || '');
  const m2 = raw.match(/Source URL:\s*(\S+)/i);
  return m2 ? safeHttpUrl(m2[1]) : null;
}

/**
 * @param {object[]} sourceRows
 * @returns {{ document_id: unknown, title: string, url: string | null }[]}
 */
export function collectWikiEvidenceEntries(sourceRows) {
  return (sourceRows || []).map((r) => ({
    document_id: r.id,
    title: r.title || 'Source',
    url: evidenceUrlFromDocumentRow(r),
  }));
}

function formatEvidenceSectionMarkdown(sourceRows) {
  const entries = collectWikiEvidenceEntries(sourceRows);
  if (entries.length === 0) return '';
  const lines = ['', '## Evidence', ''];
  for (const e of entries) {
    if (e.url) {
      const safeTitle = String(e.title).replace(/[\[\]]/g, '');
      lines.push(`- [${safeTitle}](${e.url})`);
    } else {
      lines.push(`- ${e.title} (internal source)`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

function deterministicCompileFallback(sourceDocs, suggestedTitle) {
  const lines = sourceDocs
    .flatMap((d) => String(d.raw_text || '').split('\n'))
    .map((l) => l.trim())
    .filter(Boolean);
  const actionLines = lines.filter((l) => /action item|todo|next step|owner:/i.test(l)).slice(0, 8);
  const decisionLines = lines.filter((l) => /decid|agreed|ship|plan|will /i.test(l)).slice(0, 8);
  const keyPoints = lines.filter((l) => l.length > 30).slice(0, 12);
  const sourceTitles = sourceDocs.map((d) => d.title).filter(Boolean);
  return [
    `# ${suggestedTitle}`,
    '',
    '## Overview',
    `Compiled from ${sourceDocs.length} source document(s): ${sourceTitles.join(', ') || 'untitled sources'}.`,
    '',
    '## Key Points',
    ...(keyPoints.length ? keyPoints.map((k) => `- ${k}`) : ['- No key points extracted.']),
    '',
    '## Decisions',
    ...(decisionLines.length ? decisionLines.map((d) => `- ${d}`) : ['- No explicit decisions extracted.']),
    '',
    '## Action Items',
    ...(actionLines.length ? actionLines.map((a) => `- ${a}`) : ['- No explicit action items extracted.']),
    '',
    '## Open Questions',
    '- Review this page with a human editor and fill any missing context.',
    '',
    '## Sources',
    ...sourceTitles.map((t) => `- ${t}`),
  ].join('\n');
}

/**
 * Extract [[wikilinks]] deterministically from compiled markdown.
 * Linus requirement: do NOT let the LLM generate relationship edges.
 * Extract them from the actual text after compilation.
 *
 * @param {string} markdown - Compiled article text
 * @returns {string[]} Array of linked article names (deduplicated)
 */
export function extractWikilinks(markdown) {
  const links = new Set();
  // Match [[link]] and [[link|display]] patterns
  const regex = /\[\[([^\]|]+?)(?:\|[^\]]+)?\]\]/g;
  let match;
  while ((match = regex.exec(markdown)) !== null) {
    links.add(match[1].trim());
  }
  return [...links];
}

/**
 * Get the maximum classification from a list of classifications.
 * @param {string[]} classifications
 * @returns {string}
 */
function maxClassification(classifications) {
  let maxIdx = 0;
  for (const c of classifications) {
    const idx = CLASSIFICATION_ORDER.indexOf(c);
    if (idx > maxIdx) maxIdx = idx;
  }
  return CLASSIFICATION_ORDER[maxIdx];
}

function inferFolderSlugFromSources(sourceDocs) {
  const joined = sourceDocs.map((d) => `${d.title || ''} ${d.source || ''}`).join(' ').toLowerCase();
  if (joined.includes('meeting') || joined.includes('tldv') || joined.includes('transcript')) return 'meetings';
  if (joined.includes('campaign')) return 'research';
  if (joined.includes('decision') || joined.includes('adr')) return 'decisions';
  if (joined.includes('process') || joined.includes('runbook') || joined.includes('sop')) return 'processes';
  if (joined.includes('contact') || joined.includes('stakeholder') || joined.includes('customer')) return 'contacts';
  return 'research';
}

/** Normalizes wikilink targets to wiki_pages.slug (shared with API + Board). */
export function toSlug(input) {
  return String(input || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 120) || 'wiki-page';
}

/**
 * STAQPRO-315: stable-sort vault docs to the front of a row array, in place.
 * Used by compileCluster so wiki_pages.source_document_id captures the
 * curated vault note when a cluster mixes vault and non-vault sources.
 *
 * Stable: non-vault relative order is preserved (Node's sort is stable),
 * and vault docs retain their original relative order among themselves.
 *
 * @param {Array<{source?: string}>} rows
 * @returns {Array} the same array, mutated.
 */
export function preferVaultAnchor(rows) {
  if (!Array.isArray(rows) || rows.length < 2) return rows;
  rows.sort((a, b) => {
    const av = a && a.source === 'vault' ? 0 : 1;
    const bv = b && b.source === 'vault' ? 0 : 1;
    return av - bv;
  });
  return rows;
}

/** Test-only export: see `preferVaultAnchor` callers in compileCluster. */
export function _clusterSourceFingerprintForTest(rows) {
  return clusterSourceFingerprint(rows);
}

/** SHA-256 of sorted source ids + raw_text — skip recompile when unchanged. */
function clusterSourceFingerprint(rows) {
  const h = createHash('sha256');
  const sorted = [...rows].sort((a, b) => String(a.id).localeCompare(String(b.id)));
  for (const r of sorted) {
    h.update(String(r.id));
    h.update('\0');
    h.update(String(r.raw_text || ''));
    h.update('\n');
  }
  return h.digest('hex');
}

/**
 * Compile a single cluster of documents into a wiki article.
 *
 * @param {Object} cluster - From clusterDocuments()
 * @param {Object} opts
 * @param {string} [opts.writtenBy='wiki-compiler'] - Attribution
 * @returns {Promise<{ documentId: string, title: string, wikilinks: string[], classification: string } | null>}
 */
async function compileCluster(cluster, opts = {}) {
  const writtenBy = opts.writtenBy || 'wiki-compiler';

  // 1. Read source document texts
  const docIds = cluster.docs.map(d => d.id);
  const sourceDocs = await query(
    `SELECT id, title, raw_text, classification, source, metadata
     FROM content.documents
     WHERE id = ANY($1)`,
    [docIds]
  );

  if (sourceDocs.rows.length === 0) return null;

  // Deterministic order: same as cluster (SQL ANY order is not stable). Fingerprint + primary source must match upsert.
  const byId = new Map(sourceDocs.rows.map((r) => [String(r.id), r]));
  const orderedSourceRows = [];
  for (const id of docIds) {
    const row = byId.get(String(id));
    if (row) orderedSourceRows.push(row);
  }

  // STAQPRO-315: prefer vault docs as the anchor (orderedSourceRows[0] becomes
  // wiki_pages.source_document_id). Without this, the greedy clusterer picks the
  // most-connected doc as anchor — usually an email summary or TLDv transcript
  // — and the curated vault note becomes a secondary source invisible to
  // `wiki_pages.source_document_id` lookups. Stable-sort keeps the rest of the
  // order intact for diff readability. Fingerprint is order-independent
  // (clusterSourceFingerprint sorts ids), so this never causes a re-compile loop.
  preferVaultAnchor(orderedSourceRows);

  const compileFingerprint = clusterSourceFingerprint(orderedSourceRows);
  const primarySourceId = orderedSourceRows[0]?.id;
  if (primarySourceId) {
    const skipR = await query(
      `SELECT id FROM content.wiki_pages
       WHERE source_document_id::text = $1::text
         AND compile_source_fingerprint = $2
         AND compiled_at IS NOT NULL
       LIMIT 1`,
      [String(primarySourceId), compileFingerprint]
    );
    if (skipR.rows.length > 0) {
      log.info(`Skip compile "${cluster.topTitle}" — source fingerprint unchanged`);
      return null;
    }
  }

  // 2. Build LLM prompt with source material
  const sourceTexts = orderedSourceRows.map(d =>
    `--- SOURCE: ${d.title} ---\n${d.raw_text.slice(0, 8000)}\n--- END ---`
  ).join('\n\n');

  const suggestedTitle = cluster.topTitle
    .replace(/^vault:/, '')
    .replace(/\//g, ' — ')
    .replace(/\.md$/, '');

  const userPrompt = `Compile the following ${orderedSourceRows.length} source document(s) into a structured wiki article.

Suggested title: "${suggestedTitle}"

Use this template:
${COMPILE_TEMPLATE}

Source material:

${sourceTexts}`;

  // 3. G1 budget check
  await loadGuardCheck();
  if (guardCheck) {
    const check = await guardCheck({ action: 'llm_call', agent: 'wiki-compiler', estimatedCost: 0.01 });
    if (!check.allowed) {
      log.warn(`G1 budget gate blocked compilation of "${suggestedTitle}"`);
      return null;
    }
  }

  // 4. LLM compile
  let articleText = null;
  try {
    const models = await loadModelsConfig();
    const llm = createLLMClient(COMPILE_MODEL, models);
    const response = await callProvider(llm, {
      system: COMPILE_SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userPrompt }],
      maxTokens: 4000,
      temperature: 0.3,
    });
    articleText = response.text;
  } catch (err) {
    log.warn(`LLM compile unavailable (${err.message}) — using deterministic fallback for "${suggestedTitle}"`);
    articleText = deterministicCompileFallback(orderedSourceRows, suggestedTitle);
  }

  if (!articleText || articleText.trim().length < 50) {
    log.warn(`LLM produced empty/tiny output for "${suggestedTitle}"`);
    return null;
  }

  // 5. Strip machine-readable signal fence, merge defaults, append Evidence + Signal assessment
  const { remainder: bodyWithoutFence, yaml: signalYaml } = extractWikiSignalFence(articleText);
  const parsedFence = signalYaml ? parseSignalYamlLines(signalYaml) : {};
  let wikiSignal = mergeWikiSignal(parsedFence, orderedSourceRows);

  const bodyMain = bodyWithoutFence.trim();
  if (!bodyMain || bodyMain.length < 50) {
    log.warn(`Compiled body too short after signal extraction for "${suggestedTitle}"`);
    return null;
  }

  const evidenceMd = formatEvidenceSectionMarkdown(orderedSourceRows);

  await loadSanitizer();
  let combinedBody = `${bodyMain}${evidenceMd}`;
  if (sanitize) {
    combinedBody = sanitize(combinedBody);
    wikiSignal = {
      ...wikiSignal,
      rationale: sanitize(String(wikiSignal.rationale || '').slice(0, 500)).slice(0, 500),
    };
  }
  articleText = `${combinedBody.trim()}${formatSignalAssessmentSection(wikiSignal)}`.trimEnd();

  // 6. Classification propagation: max(source classifications)
  const sourceClassifications = orderedSourceRows.map(d => d.classification || 'INTERNAL');
  let articleClassification = maxClassification(sourceClassifications);

  // PII check on compiled output
  if (detectPII) {
    const piiResult = detectPII(articleText);
    if (piiResult.hasPII) {
      articleClassification = maxClassification([articleClassification, 'CONFIDENTIAL']);
      log.warn(`PII detected in compiled article "${suggestedTitle}" → ${articleClassification}`);
    }
  }

  // 7. Extract wikilinks deterministically from text
  const wikilinks = extractWikilinks(articleText);

  // 8. Build YAML frontmatter
  const now = new Date().toISOString().split('T')[0];
  const compileTags = ['wiki', 'compiled', ...wikiSignal.tags.filter((t) => t !== 'wiki' && t !== 'compiled')];
  const frontmatter = [
    '---',
    `title: "${suggestedTitle}"`,
    `created: ${now}`,
    `updated: ${now}`,
    `type: compiled`,
    `sources:`,
    ...orderedSourceRows.map(d => `  - "${d.title}"`),
    'tags:',
    ...compileTags.map((t) => `  - ${t}`),
    `signal_confidence: ${wikiSignal.confidence}`,
    `signal_actionability: ${wikiSignal.actionability}`,
    wikilinks.length > 0 ? `related:\n${wikilinks.map(l => `  - "[[${l}]]"`).join('\n')}` : '',
    `classification: ${articleClassification}`,
    `compiled_by: ${writtenBy}`,
    `summary: "Compiled from ${orderedSourceRows.length} source(s): ${orderedSourceRows.map(d => d.title).slice(0, 3).join(', ')}"`,
    '---',
    '',
  ].filter(Boolean).join('\n');

  const fullArticle = frontmatter + articleText;

  // 9. Ingest compiled article back into knowledge base
  const sourceSlug = suggestedTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 80);
  const result = await ingestDocument({
    source: 'wiki-compiled',
    sourceId: `wiki:${sourceSlug}`,
    title: suggestedTitle,
    rawText: fullArticle,
    format: 'obsidian', // Reuse obsidian normalizer for the compiled markdown
    metadata: {
      compiled_from: docIds,
      wikilinks,
      compiled_by: writtenBy,
      compile_date: now,
      signal_tags: wikiSignal.tags,
      signal_confidence: wikiSignal.confidence,
      signal_actionability: wikiSignal.actionability,
      signal_rationale: wikiSignal.rationale,
      evidence: collectWikiEvidenceEntries(orderedSourceRows),
    },
    classification: articleClassification,
    forceUpdate: true, // Always overwrite previous compilation
  });

  if (!result) return null;

  // 10. Create/update structured wiki page (hierarchical vault)
  const articleSlug = toSlug(suggestedTitle);
  const folderSlug = inferFolderSlugFromSources(orderedSourceRows);
  const nowTs = new Date().toISOString();
  let parentId = null;
  if (opts.projectId) {
    const parentR = await query(
      `SELECT id FROM content.wiki_pages
       WHERE project_id::text = $1::text AND slug = $2
       LIMIT 1`,
      [opts.projectId, folderSlug]
    );
    parentId = parentR.rows[0]?.id || null;
  }
  await query(
    `INSERT INTO content.wiki_pages
       (project_id, parent_id, slug, title, content, classification, is_index, compiled_at, source_document_id, compile_source_fingerprint, created_by, updated_by)
     VALUES ($1, $2, $3, $4, $5, $6, false, $7, $8, $9, $10, $10)
     ON CONFLICT (project_id, slug)
     DO UPDATE SET
       parent_id = EXCLUDED.parent_id,
       title = EXCLUDED.title,
       content = EXCLUDED.content,
       classification = EXCLUDED.classification,
       compiled_at = EXCLUDED.compiled_at,
       source_document_id = EXCLUDED.source_document_id,
       compile_source_fingerprint = EXCLUDED.compile_source_fingerprint,
       updated_by = EXCLUDED.updated_by,
       updated_at = now()`,
    [
      opts.projectId || null,
      parentId,
      articleSlug,
      suggestedTitle,
      articleText,
      articleClassification,
      nowTs,
      orderedSourceRows[0]?.id || null,
      compileFingerprint,
      writtenBy,
    ]
  );

  // 11. Mark compiled article as 'skip' (anti-circular-ingestion)
  await query(
    `UPDATE content.documents SET compile_status = 'skip', compiled_from = $2 WHERE id = $1`,
    [result.documentId, docIds]
  );

  // 12. Mark source documents as compiled
  await query(
    `UPDATE content.documents SET compile_status = 'compiled' WHERE id = ANY($1)`,
    [docIds]
  );

  log.info(`Compiled "${suggestedTitle}" from ${docIds.length} sources → ${result.chunkCount} chunks (${articleClassification})`);

  return {
    documentId: result.documentId,
    title: suggestedTitle,
    wikilinks,
    classification: articleClassification,
    sourceCount: docIds.length,
    chunkCount: result.chunkCount,
    signal: wikiSignal,
  };
}

/**
 * Run the full wiki compilation pipeline.
 *
 * @param {Object} [opts]
 * @param {string} [opts.projectId] - Scope to a specific project
 * @param {number} [opts.maxArticles] - Max articles to compile per run (default 20)
 * @param {string} [opts.writtenBy] - Attribution (default 'wiki-compiler')
 * @returns {Promise<{ compiled: number, skipped: number, errors: number, articles: Array }>}
 */
export async function compileWiki(opts = {}) {
  const maxArticles = opts.maxArticles ?? 20;

  log.info(`Starting compilation${opts.projectId ? ` for project ${opts.projectId}` : ''}`);

  // 1. Cluster pending documents
  const clusters = await clusterDocuments({
    projectId: opts.projectId,
  });

  if (clusters.length === 0) {
    log.info('No pending documents to compile');
    return { compiled: 0, skipped: 0, errors: 0, articles: [] };
  }

  log.info(`${clusters.length} clusters to compile (max ${maxArticles})`);

  // 2. Compile each cluster (sequentially to respect G1 budget)
  const articles = [];
  let errors = 0;
  let skipped = 0;

  for (const cluster of clusters.slice(0, maxArticles)) {
    try {
      const result = await compileCluster(cluster, opts);
      if (result) {
        articles.push(result);
      } else {
        skipped++;
      }
    } catch (err) {
      log.error(`Failed to compile cluster "${cluster.topTitle}": ${err.message}`);
      errors++;
    }
  }

  if (clusters.length > maxArticles) {
    skipped += clusters.length - maxArticles;
  }

  log.info(`Done: ${articles.length} compiled, ${skipped} skipped, ${errors} errors`);

  return {
    compiled: articles.length,
    skipped,
    errors,
    articles,
  };
}

/**
 * Repeatedly run compileWiki for one scope until a batch compiles fewer than maxArticles clusters (or none).
 * @param {string|undefined|null} projectId - undefined/null = org-wide only (no project membership on docs)
 */
async function compileScopeUntilDrained(projectId, maxArticles, maxBatches, writtenBy) {
  const results = [];
  let compiled = 0;
  for (let i = 0; i < maxBatches; i++) {
    const result = await compileWiki({
      projectId: projectId ?? undefined,
      maxArticles,
      writtenBy,
    });
    results.push(result);
    compiled += result?.compiled || 0;
    if (!result?.compiled || result.compiled < maxArticles) break;
  }
  return { compiled, results };
}

/**
 * Drain pending wiki compiles across all scopes: org-wide documents (no project membership),
 * then each project that has at least one pending source document linked via memberships.
 *
 * Use this when the UI shows aggregate "pending" counts but a single global compile would skip project-scoped rows.
 *
 * @param {Object} [opts]
 * @param {number} [opts.maxArticles]
 * @param {number} [opts.maxBatchesPerScope] - max inner poll loops per scope (default 50)
 * @param {string} [opts.writtenBy]
 */
export async function compileWikiAllPendingScopes(opts = {}) {
  const maxArticles = opts.maxArticles ?? 20;
  const maxBatches = opts.maxBatchesPerScope ?? 50;
  const writtenBy = opts.writtenBy || 'wiki-compiler';

  const flatResults = [];
  let totalCompiled = 0;

  const orgPass = await compileScopeUntilDrained(undefined, maxArticles, maxBatches, writtenBy);
  totalCompiled += orgPass.compiled;
  for (const r of orgPass.results) {
    flatResults.push({ scope: 'org', ...r });
  }

  const projRes = await query(
    `SELECT DISTINCT pm.project_id::text AS id
     FROM agent_graph.project_memberships pm
     INNER JOIN content.documents d ON d.id::text = pm.entity_id AND pm.entity_type = 'document'
     WHERE d.compile_status = 'pending'
       AND d.source != 'wiki-compiled'
     ORDER BY 1`
  );

  for (const row of projRes.rows) {
    const pass = await compileScopeUntilDrained(row.id, maxArticles, maxBatches, writtenBy);
    totalCompiled += pass.compiled;
    for (const r of pass.results) {
      flatResults.push({ scope: `project:${row.id}`, ...r });
    }
  }

  return {
    compiled: totalCompiled,
    batches: flatResults.length,
    results: flatResults,
  };
}

/**
 * Get compilation status summary for a project or globally.
 *
 * @param {string} [projectId]
 * @returns {Promise<{ pending: number, compiled: number, wikiArticles: number }>}
 */
export async function getCompileStatus(projectId) {
  const base = projectId
    ? `SELECT compile_status, count(*) AS count FROM content.documents d
       WHERE d.id::text IN (
         SELECT pm.entity_id
         FROM agent_graph.project_memberships pm
         WHERE pm.project_id = $1 AND pm.entity_type = 'document'
       ) OR d.source = 'wiki-compiled'
       GROUP BY compile_status`
    : `SELECT compile_status, count(*) AS count FROM content.documents GROUP BY compile_status`;

  const result = await query(base, projectId ? [projectId] : []);
  const counts = Object.fromEntries(result.rows.map(r => [r.compile_status || 'none', parseInt(r.count)]));

  // Count wiki-compiled articles separately
  const wikiResult = await query(
    `SELECT count(*) FROM content.documents WHERE source = 'wiki-compiled'`
  );

  return {
    pending: counts.pending || 0,
    compiled: counts.compiled || 0,
    wikiArticles: parseInt(wikiResult.rows[0]?.count || '0'),
    none: counts.none || 0,
  };
}
