#!/usr/bin/env node
/**
 * Setup for the test sender account (e.g., gang@jiffyautoglass.com).
 * Uses SMTP with a Google App Password — no OAuth consent screen needed.
 *
 * Setup (one-time):
 *   1. Go to https://myaccount.google.com/apppasswords
 *      (sign in as gang@jiffyautoglass.com)
 *   2. Create an App Password (name it "AutoBot Test Sender" or similar)
 *   3. Copy the 16-character password
 *   4. Run: node tools/setup-sender.js
 *      (it will prompt you for the email and app password)
 *
 * Note: 2-Step Verification must be enabled on the account first.
 * Enable it at: https://myaccount.google.com/signinoptions/two-step-verification
 */

import { writeFileSync, existsSync, readFileSync } from 'fs';
import { createInterface } from 'readline';
import { createTransport } from 'nodemailer';

const ENV_PATH = new URL('../.env.sender', import.meta.url);

function prompt(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function main() {
  console.log('AutoBot Inbox — Sender Account Setup (SMTP)');
  console.log('============================================\n');

  // Check for existing config
  let existingEmail = '';
  let existingPassword = '';
  if (existsSync(ENV_PATH)) {
    try {
      const content = readFileSync(ENV_PATH, 'utf-8');
      existingEmail = content.match(/SENDER_EMAIL=(.+)/)?.[1]?.trim() || '';
      existingPassword = content.match(/SENDER_APP_PASSWORD=(.+)/)?.[1]?.trim() || '';
    } catch { /* ignore */ }
  }

  if (existingEmail && existingPassword) {
    console.log(`Existing config found: ${existingEmail}`);
    const reuse = await prompt('Use existing config? (y/n): ');
    if (reuse.toLowerCase() === 'y') {
      console.log('\nVerifying connection...');
      await verify(existingEmail, existingPassword);
      return;
    }
  }

  console.log('Prerequisites:');
  console.log('  1. Enable 2-Step Verification on the sender Google account');
  console.log('     https://myaccount.google.com/signinoptions/two-step-verification');
  console.log('  2. Create an App Password at:');
  console.log('     https://myaccount.google.com/apppasswords');
  console.log('  3. Copy the 16-character password\n');

  const email = await prompt('Sender email (e.g., gang@jiffyautoglass.com): ');
  const appPassword = await prompt('App Password (16 chars, no spaces): ');

  if (!email || !appPassword) {
    console.error('Email and App Password are required.');
    process.exit(1);
  }

  console.log('\nVerifying connection...');
  await verify(email, appPassword);

  // Save to .env.sender
  const envContent = [
    '# Sender account SMTP credentials (for test emails)',
    '# Generated by: node tools/setup-sender.js',
    `SENDER_EMAIL=${email}`,
    `SENDER_APP_PASSWORD=${appPassword}`,
    '',
  ].join('\n');
  writeFileSync(ENV_PATH, envContent);

  console.log(`\nCredentials saved to .env.sender`);
  console.log('You can now run: node tools/send-test-emails.js');
}

async function verify(email, appPassword) {
  const transporter = createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
      user: email,
      pass: appPassword,
    },
  });

  try {
    await transporter.verify();
    console.log(`  Connected to SMTP as ${email}`);
  } catch (err) {
    console.error(`  SMTP connection failed: ${err.message}`);
    console.error('\nTroubleshooting:');
    console.error('  - Make sure 2-Step Verification is enabled');
    console.error('  - Make sure the App Password is correct (16 chars, no spaces)');
    console.error('  - If using Google Workspace, admin may need to allow "Less secure apps"');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
